name: social_xp
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  auto_route: ^5.0.1
  rxdart: ^0.27.4
  mocktail: ^0.3.0
  mockito: ^5.3.0
  bloc_test: ^9.1.0
  flutter_svg: ^1.1.5
  page_view_indicators: ^2.0.0
  intl: ^0.17.0
  flutter_html: ^3.0.0-alpha.6
  url_launcher: ^6.1.6
  video_player: ^2.4.7
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.2
  dotted_border: ^2.0.0+3
  image_picker: ^0.8.6
  cropperx: ^1.1.1
  permission_handler: ^10.2.0
  flutter_easyloading: ^3.0.5
  flutter_keyboard_visibility: ^5.4.0
  agora_rtc_engine: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true
  generate: true
  